# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Shelter.create(name: 'Alamo Lake Dog Haven', address: '12 Ferry Avenue', city: 'Cincinnati', state: 'Ohio', zip: 45219)
Shelter.create(name: 'Alcova Dog Shelter', address: '67 Jefferson Lane', city: 'El Paso', state: 'Texas', zip: 79901)
Shelter.create(name: 'Alpine Northeast Dog Haven', address: '25 Jessie Avenue', city: 'Springfield', state: 'Massachusetts', zip: 21151)
Shelter.create(name: 'Anoka Dog Sanctuary', address: '60 Loma Street', city: 'Dallas', state: 'Texas', zip: 75287)
Shelter.create(name: 'Antelope Hills Dog Sanctuary', address: '41 Renfrow Street', city: 'Tucson', state: 'Arizona', zip: 85705)
Shelter.create(name: 'Atlantic City Dog Sanctuary', address: '59 Pine Valley Street', city: 'Sarasota', state: 'Florida', zip: 34232)
Shelter.create(name: 'Beluga Dog Shelter', address: '72 Strong Lane', city: 'Indianapolis', state: 'Indiana', zip: 46218)
Shelter.create(name: 'Birch Creek Dog Haven', address: '11 Corning Avenue', city: 'Milwaukee', state: 'Wisconsin', zip: 53203)
Shelter.create(name: 'Bondurant Dog Shelter', address: '78 Pillsbury Lane', city: 'Colorado Springs', state: 'Colorado', zip: 80951)
Shelter.create(name: 'Boulder Dog Sanctuary', address: '43 Lake Buena Vista Street', city: 'Rochester', state: 'New York', zip: 14608)
Shelter.create(name: 'Bowden Dog Sanctuary', address: '54 Meyer Street', city: 'Buffalo', state: 'New York', zip: 14208)
Shelter.create(name: 'Brownlee Dog Haven', address: '25 New Holland Avenue', city: 'Minneapolis', state: 'Minnesota', zip: 55403)
Shelter.create(name: 'Brundage Dog Haven', address: '4 Zarephath Avenue', city: 'Reno', state: 'Nevada', zip: 89521)
Shelter.create(name: 'Butterfield Dog Sanctuary', address: '44 Topock Street', city: 'Las Vegas', state: 'Nevada', zip: 89107)
Shelter.create(name: 'Canova Dog Haven', address: '13 Junction City Avenue', city: 'Baton Rouge', state: 'Louisiana', zip: 70836)
Shelter.create(name: 'Carter Dog Sanctuary', address: '53 Kingston Street', city: 'Allentown', state: 'Pennsylvania', zip: 18105)
Shelter.create(name: 'Cave Dog Haven', address: '24 Weed Avenue', city: 'Brooklyn', state: 'New York', zip: 11212)
Shelter.create(name: 'City of the Sun Dog Sanctuary', address: '61 Paxson Street', city: 'Ogden', state: 'Utah', zip: 84404)
Shelter.create(name: 'Cobre Dog Haven', address: '20 Burton Avenue', city: 'Worcester', state: 'Massachusetts', zip: 41610)
Shelter.create(name: 'Conchas Dam Dog Shelter', address: '81 East Amana Lane', city: 'Mission Viejo', state: 'California', zip: 92692)
Shelter.create(name: 'Cuevitas Dog Shelter', address: '77 Knowles Lane', city: 'Des Moines', state: 'Iowa', zip: 50309)
Shelter.create(name: 'Donald Dog Sanctuary', address: '40 Whitmer Street', city: 'Memphis', state: 'Tennessee', zip: 38120)
Shelter.create(name: 'Escondida Dog Shelter', address: '96 Valley Ranch Lane', city: 'Palm Bay', state: 'Florida', zip: 32909)
Shelter.create(name: 'Fontenelle Dog Haven', address: '29 Thomasville Avenue', city: 'Omaha', state: 'Nebraska', zip: 68112)
Shelter.create(name: 'Freeport Dog Shelter', address: '81 Santa Cruz Lane', city: 'Cleveland', state: 'Ohio', zip: 44135)
Shelter.create(name: 'Funkley Dog Haven', address: '29 San Antonio Avenue', city: 'Queens', state: 'New York', zip: 11361)
Shelter.create(name: 'Gann Valley Dog Shelter', address: '71 Kief Lane', city: 'Riverside', state: 'California', zip: 92508)
Shelter.create(name: 'Garfield Dog Shelter', address: '68 Albee Lane', city: 'Tampa', state: 'Florida', zip: 33637)
Shelter.create(name: 'Garfield Dog Shelter', address: '100 Larson Lane', city: 'Provo', state: 'Utah', zip: 84604)
Shelter.create(name: 'Gross Dog Shelter', address: '99 Towner Lane', city: 'Columbus', state: 'Ohio', zip: 43026)
Shelter.create(name: 'Guerra Dog Shelter', address: '76 Farmer Lane', city: 'Denton', state: 'Texas', zip: 76207)
Shelter.create(name: 'Hawk Springs Dog Shelter', address: '68 Charco Lane', city: 'Hartford', state: 'Connecticut', zip: 06106)
Shelter.create(name: 'Healy Lake Dog Shelter', address: '90 Plevna Lane', city: 'San Antonio', state: 'Texas', zip: 78112)
Shelter.create(name: 'Heimdal Dog Sanctuary', address: '50 Weeki Wachee Street', city: 'Sacramento', state: 'California', zip: 95820)
Shelter.create(name: 'Helen Dog Shelter', address: '83 Valley City Lane', city: 'Bridgeport', state: 'Connecticut', zip: 06605)
Shelter.create(name: 'Hillside Acres Dog Sanctuary', address: '65 Abeytas Street', city: 'Port St. Lucie', state: 'Florida', zip: 34986)
Shelter.create(name: 'Hillsview Dog Haven', address: '16 Bettles Avenue', city: 'Austin', state: 'Texas', zip: 78749)
Shelter.create(name: 'Hoot Owl Dog Haven', address: '16 Amistad Avenue', city: 'Orlando', state: 'Florida', zip: 32829)
Shelter.create(name: 'Huntley Dog Shelter', address: '98 Conway Lane', city: 'Dayton', state: 'Ohio', zip: 45432)
Shelter.create(name: 'Jeffrey City Dog Sanctuary', address: '46 Excello Street', city: 'McAllen', state: 'Texas', zip: 78573)
Shelter.create(name: 'Kelly Dog Sanctuary', address: '47 Ugashik Street', city: 'Cape Coral', state: 'Florida', zip: 33991)
Shelter.create(name: 'Ketron Island Dog Sanctuary', address: '46 Milltown Street', city: 'Salt Lake City', state: 'Utah', zip: 84116)
Shelter.create(name: 'Lake Roberts Dog Shelter', address: '74 Athelstan Lane', city: 'Wichita', state: 'Kansas', zip: 67230)
Shelter.create(name: 'Lambert Dog Haven', address: '2 Beaconsfield Avenue', city: 'Boston', state: 'Massachusetts', zip: 02120)
Shelter.create(name: 'Laurier Dog Haven', address: '8 Bartow Avenue', city: 'Nashville', state: 'Tennessee', zip: 37027)
Shelter.create(name: 'Lily Dog Shelter', address: '76 Gulkana Lane', city: 'Pittsburgh', state: 'Pennsylvania', zip: 15216)
Shelter.create(name: 'Lime Village Dog Sanctuary', address: '62 Virgil Street', city: 'Chicago', state: 'Illinois', zip: 60018)
Shelter.create(name: 'Lonetree Dog Sanctuary', address: '60 Lost River Street', city: 'Fort Worth', state: 'Texas', zip: 76164)
Shelter.create(name: 'Los Lobos Dog Sanctuary', address: '60 Waldron Street', city: 'Long Beach', state: 'California', zip: 90822)
Shelter.create(name: 'Lost Springs Dog Haven', address: '26 Le Roy Avenue', city: 'St. Louis', state: 'Missouri', zip: 63110)
Shelter.create(name: 'Lotsee Dog Sanctuary', address: '39 Megargel Street', city: 'Virginia Beach', state: 'Virginia', zip: 23459)
Shelter.create(name: 'Lower Frisco Dog Sanctuary', address: '46 Lance Creek Street', city: 'Bakersfield', state: 'California', zip: 93306)
Shelter.create(name: 'Lowry Dog Sanctuary', address: '36 Cooperton Street', city: 'Seattle', state: 'Washington', zip: 98109)
Shelter.create(name: 'Manzano Dog Sanctuary', address: '42 Stevens Village Street', city: 'New Haven', state: 'Connecticut', zip: 66519)
Shelter.create(name: 'Marblemount Dog Sanctuary', address: '44 Pine Island Street', city: 'Richmond', state: 'Virginia', zip: 23222)
Shelter.create(name: 'Martinez Dog Haven', address: '20 River Bend Avenue', city: 'Staten Island', state: 'New York', zip: 10302)
Shelter.create(name: 'McKinnon Dog Sanctuary', address: '46 Cartago Street', city: 'Grand Rapids', state: 'Michigan', zip: 49546)
Shelter.create(name: 'McLeod Dog Sanctuary', address: '44 Onaka Street', city: 'San Diego', state: 'California', zip: 92109)
Shelter.create(name: 'Moclips Dog Sanctuary', address: '45 Churchs Ferry Street', city: 'Raleigh', state: 'North Carolina', zip: 27617)
Shelter.create(name: 'Monowi Dog Haven', address: '6 Champ Avenue', city: 'Providence', state: 'Rhode Island', zip: 92903)
Shelter.create(name: 'Newkirk Dog Shelter', address: '98 Raleigh Lane', city: 'Akron', state: 'Ohio', zip: 44306)
Shelter.create(name: 'Oakley Dog Shelter', address: '84 Loveland Lane', city: 'Honolulu', state: 'Hawaii', zip: 96859)
Shelter.create(name: 'Odanah Dog Haven', address: '31 Valdez Avenue', city: 'Oklahoma City', state: 'Oklahoma', zip: 73012)
Shelter.create(name: 'Orin Dog Sanctuary', address: '56 Guadalupe Guerra Street', city: 'Tulsa', state: 'Oklahoma', zip: 74133)
Shelter.create(name: 'Owl Creek Dog Haven', address: '23 Kinbrae Avenue', city: 'Albuquerque', state: 'New Mexico', zip: 87121)
Shelter.create(name: 'Oyehut Dog Sanctuary', address: '45 Venturia Street', city: 'Louisville', state: 'Kentucky', zip: 40177)
Shelter.create(name: 'Pastura Dog Haven', address: '12 Dalton Avenue', city: 'Los Angeles', state: 'California', zip: 90291)
Shelter.create(name: 'Pecan Park Dog Shelter', address: '99 Tonsina Lane', city: 'Columbia', state: 'South Carolina', zip: 29202)
Shelter.create(name: 'Pinhook Dog Sanctuary', address: '44 Cedar Street', city: 'Jacksonville', state: 'Florida', zip: 32224)
Shelter.create(name: 'Pinon Dog Haven', address: '8 Centralia Avenue', city: 'Mesa', state: 'Arizona', zip: 85208)
Shelter.create(name: 'Posey Dog Sanctuary', address: '66 Van Tassell Street', city: 'Denver', state: 'Colorado', zip: 80264)
Shelter.create(name: 'Poso Park Dog Shelter', address: '94 Valley-Hi Lane', city: 'Washington', state: 'District of Columbia', zip: 20010)
Shelter.create(name: 'Powder River Dog Haven', address: '27 Hope Avenue', city: 'Concord', state: 'California', zip: 94518)
Shelter.create(name: 'Pueblo Dog Shelter', address: '97 McBaine Lane', city: 'Albany', state: 'New York', zip: 12208)
Shelter.create(name: 'Quail Dog Haven', address: '31 Clear Creek Avenue', city: 'Portland', state: 'Oregon', zip: 97227)
Shelter.create(name: 'Regina Dog Haven', address: '31 Deputy Avenue', city: 'Murrieta', state: 'California', zip: 92563)
Shelter.create(name: 'Rentchler Dog Haven', address: '24 McGee Creek Avenue', city: 'Atlanta', state: 'Georgia', zip: 30334)
Shelter.create(name: 'Rivers Dog Shelter', address: '74 Roy Lake Lane', city: 'Knoxville', state: 'Tennessee', zip: 37918)
Shelter.create(name: 'Roswell Dog Haven', address: '9 Dresser Avenue', city: 'Bronx', state: 'New York', zip: 10453)
Shelter.create(name: 'Ruso Dog Sanctuary', address: '34 Girard Street', city: 'San Jose', state: 'California', zip: 95118)
Shelter.create(name: 'Ryan Park Dog Haven', address: '0 St. Charles Avenue', city: 'Birmingham', state: 'Alabama', zip: 35218)
Shelter.create(name: 'Silvana Dog Sanctuary', address: '57 Chicken Street', city: 'New Orleans', state: 'Louisiana', zip: 70139)
Shelter.create(name: 'Sunset Acres Dog Sanctuary', address: '50 Cottonwood Street', city: 'Madison', state: 'Wisconsin', zip: 53706)
Shelter.create(name: 'Sutton Dog Haven', address: '10 Leith Avenue', city: 'Miami', state: 'Florida', zip: 33129)
Shelter.create(name: 'Table Rock Dog Shelter', address: '74 Dering Harbor Lane', city: 'Charleston', state: 'South Carolina', zip: 29414)
Shelter.create(name: 'Tanquecitos South Acres II Dog Shelter', address: '68 Greenhorn Lane', city: 'Harrisburg', state: 'Pennsylvania', zip: 17101)
Shelter.create(name: 'Tavistock Dog Haven', address: '32 Huson Avenue', city: 'Detroit', state: 'Michigan', zip: 48209)
Shelter.create(name: 'The Ranch Dog Shelter', address: '94 Kaskaskia Lane', city: 'Charlotte', state: 'North Carolina', zip: 28269)
Shelter.create(name: 'Three Creeks Dog Sanctuary', address: '52 Port Tobacco Village Street', city: 'Phoenix', state: 'Arizona', zip: 85008)
Shelter.create(name: 'Thurmond Dog Shelter', address: '68 Barry Lane', city: 'San Francisco', state: 'California', zip: 94130)
Shelter.create(name: 'Tierra Dorada Dog Shelter', address: '69 Niarada Lane', city: 'Greenville', state: 'South Carolina', zip: 29614)
Shelter.create(name: 'Trout Valley Dog Shelter', address: '84 Keeler Lane', city: 'Toledo', state: 'Ohio', zip: 43615)
Shelter.create(name: 'Valle Verde Dog Sanctuary', address: '57 Silver Gate Street', city: 'Little Rock', state: 'Arkansas', zip: 72211)
Shelter.create(name: 'Verdon Dog Shelter', address: '73 Hannah Lane', city: 'Baltimore', state: 'Maryland', zip: 21218)
Shelter.create(name: 'Warm River Dog Shelter', address: '80 Whale Pass Lane', city: 'Manhattan', state: 'New York', zip: 10026)
Shelter.create(name: 'Westerville Dog Shelter', address: '90 Gascoyne Lane', city: 'Houston', state: 'Texas', zip: 77069)
Shelter.create(name: 'Westlake Dog Haven', address: '11 Old Eucha Avenue', city: 'New York', state: 'New York', zip: 11229)
Shelter.create(name: 'Westview Circle Dog Haven', address: '16 Duran Avenue', city: 'Fresno', state: 'California', zip: 93730)
Shelter.create(name: 'White Rock Dog Haven', address: '2 Hansboro Avenue', city: 'Kansas City', state: 'Missouri', zip: 64161)
Shelter.create(name: 'Willow Island Dog Sanctuary', address: '37 Auburn Street', city: 'Philadelphia', state: 'Pennsylvania', zip: 19154)


Pet.create(name: 'Sparky', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/west_highland_white_terrier_24.jpg', age_approx: 5, sex: 'male', breed: 'West Highland White Terrier', adoptable: true, shelter_id: 67)
Pet.create(name: 'Peppo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/mexican_hairless_105.jpg', age_approx: 13, sex: 'female', breed: 'Mexican Hairless', adoptable: false, shelter_id: 81)
Pet.create(name: 'Chayo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pomeranian_196.jpg', age_approx: 12, sex: 'male', breed: 'Pomeranian', adoptable: true, shelter_id: 77)
Pet.create(name: 'Busby', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/brittany_spaniel_138.jpg', age_approx: 4, sex: 'female', breed: 'Brittany Spaniel', adoptable: true, shelter_id: 93)
Pet.create(name: 'Orsino', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/irish_terrier_90.jpg', age_approx: 2, sex: 'female', breed: 'Irish Terrier', adoptable: false, shelter_id: 59)
Pet.create(name: 'Rajnal', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bernese_mountain_dog_82.jpg', age_approx: 10, sex: 'female', breed: 'Bernese Mountain Dog', adoptable: true, shelter_id: 64)
Pet.create(name: 'Zico', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/whippet_171.jpg', age_approx: 7, sex: 'female', breed: 'Whippet', adoptable: true, shelter_id: 29)
Pet.create(name: 'Diva-Channel', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/entlebucher_92.jpg', age_approx: 6, sex: 'female', breed: 'Entlebucher', adoptable: true, shelter_id: 69)
Pet.create(name: 'Asal', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/papillon_19.jpg', age_approx: 15, sex: 'female', breed: 'Papillon', adoptable: true, shelter_id: 25)
Pet.create(name: 'Genie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/briard_38.jpg', age_approx: 1, sex: 'female', breed: 'Briard', adoptable: true, shelter_id: 54)
Pet.create(name: 'Larkin', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/redbone_50.jpg', age_approx: 10, sex: 'male', breed: 'Redbone', adoptable: true, shelter_id: 77)
Pet.create(name: 'Toga', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bull_mastiff_35.jpg', age_approx: 7, sex: 'female', breed: 'Bull Mastiff', adoptable: true, shelter_id: 45)
Pet.create(name: 'Juni', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/flat-coated_retriever_117.jpg', age_approx: 13, sex: 'male', breed: 'Flat-Coated Retriever', adoptable: true, shelter_id: 20)
Pet.create(name: 'Topher', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scottish_deerhound_95.jpg', age_approx: 5, sex: 'female', breed: 'Scottish Deerhound', adoptable: true, shelter_id: 56)
Pet.create(name: 'Jiniellyz', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/doberman_147.jpg', age_approx: 8, sex: 'female', breed: 'Doberman', adoptable: true, shelter_id: 22)
Pet.create(name: 'Cataldi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/flat-coated_retriever_28.jpg', age_approx: 13, sex: 'male', breed: 'Flat-Coated Retriever', adoptable: true, shelter_id: 62)
Pet.create(name: 'Tank', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/black-and-tan_coonhound_129.jpg', age_approx: 6, sex: 'male', breed: 'Black-And-Tan Coonhound', adoptable: true, shelter_id: 39)
Pet.create(name: 'Linus', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/appenzeller_59.jpg', age_approx: 2, sex: 'male', breed: 'Appenzeller', adoptable: true, shelter_id: 103)
Pet.create(name: 'Myshkin', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/japanese_spaniel_53.jpg', age_approx: 12, sex: 'male', breed: 'Japanese Spaniel', adoptable: true, shelter_id: 36)
Pet.create(name: 'Weenz', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/brabancon_griffon_70.jpg', age_approx: 3, sex: 'male', breed: 'Brabancon Griffon', adoptable: true, shelter_id: 104)
Pet.create(name: 'Flutie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bull_mastiff_15.jpg', age_approx: 3, sex: 'female', breed: 'Bull Mastiff', adoptable: true, shelter_id: 24)
Pet.create(name: 'Cheetha', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/great_dane_65.jpg', age_approx: 15, sex: 'male', breed: 'Great Dane', adoptable: true, shelter_id: 51)
Pet.create(name: 'Elderado', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/boston_bull_161.jpg', age_approx: 6, sex: 'female', breed: 'Boston Bull', adoptable: false, shelter_id: 100)
Pet.create(name: 'Ranea', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/blenheim_spaniel_84.jpg', age_approx: 7, sex: 'female', breed: 'Blenheim Spaniel', adoptable: true, shelter_id: 50)
Pet.create(name: 'Chuleo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pekinese_58.jpg', age_approx: 7, sex: 'male', breed: 'Pekinese', adoptable: true, shelter_id: 101)
Pet.create(name: 'Gilbert', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/papillon_108.jpg', age_approx: 12, sex: 'male', breed: 'Papillon', adoptable: true, shelter_id: 53)
Pet.create(name: 'Scallywag', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/basenji_168.jpg', age_approx: 3, sex: 'female', breed: 'Basenji', adoptable: true, shelter_id: 96)
Pet.create(name: 'Litzy', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/dhole_26.jpg', age_approx: 14, sex: 'female', breed: 'Dhole', adoptable: false, shelter_id: 39)
Pet.create(name: 'Amory', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/briard_134.jpg', age_approx: 11, sex: 'female', breed: 'Briard', adoptable: true, shelter_id: 84)
Pet.create(name: 'Morillo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/black-and-tan_coonhound_77.jpg', age_approx: 4, sex: 'male', breed: 'Black-And-Tan Coonhound', adoptable: true, shelter_id: 73)
Pet.create(name: 'Shmuely', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/labrador_retriever_123.jpg', age_approx: 15, sex: 'female', breed: 'Labrador Retriever', adoptable: true, shelter_id: 82)
Pet.create(name: 'Quintess', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/standard_poodle_96.jpg', age_approx: 15, sex: 'male', breed: 'Standard Poodle', adoptable: true, shelter_id: 89)
Pet.create(name: 'Snowden', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/schipperke_95.jpg', age_approx: 7, sex: 'female', breed: 'Schipperke', adoptable: true, shelter_id: 95)
Pet.create(name: 'Masaniello', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norwich_terrier_47.jpg', age_approx: 2, sex: 'male', breed: 'Norwich Terrier', adoptable: true, shelter_id: 73)
Pet.create(name: 'Anneeta', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/afghan_hound_121.jpg', age_approx: 1, sex: 'female', breed: 'Afghan Hound', adoptable: true, shelter_id: 25)
Pet.create(name: 'Dombi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/american_staffordshire_terrier_40.jpg', age_approx: 9, sex: 'male', breed: 'American Staffordshire Terrier', adoptable: true, shelter_id: 25)
Pet.create(name: 'Mazsola', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/american_staffordshire_terrier_42.jpg', age_approx: 1, sex: 'female', breed: 'American Staffordshire Terrier', adoptable: false, shelter_id: 60)
Pet.create(name: 'Wirginia', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/miniature_poodle_123.jpg', age_approx: 4, sex: 'female', breed: 'Miniature Poodle', adoptable: true, shelter_id: 45)
Pet.create(name: 'Fips', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/miniature_poodle_67.jpg', age_approx: 14, sex: 'male', breed: 'Miniature Poodle', adoptable: true, shelter_id: 26)
Pet.create(name: 'Vilaro', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/eskimo_dog_13.jpg', age_approx: 8, sex: 'male', breed: 'Eskimo Dog', adoptable: true, shelter_id: 66)
Pet.create(name: 'Breeder', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norwich_terrier_109.jpg', age_approx: 12, sex: 'male', breed: 'Norwich Terrier', adoptable: true, shelter_id: 26)
Pet.create(name: 'Dinky', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/dingo_104.jpg', age_approx: 14, sex: 'male', breed: 'Dingo', adoptable: true, shelter_id: 20)
Pet.create(name: 'Hernadez', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/mexican_hairless_18.jpg', age_approx: 12, sex: 'male', breed: 'Mexican Hairless', adoptable: true, shelter_id: 83)
Pet.create(name: 'Branson', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/schipperke_148.jpg', age_approx: 8, sex: 'male', breed: 'Schipperke', adoptable: true, shelter_id: 22)
Pet.create(name: 'Dotsie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/lakeland_terrier_10.jpg', age_approx: 14, sex: 'female', breed: 'Lakeland Terrier', adoptable: true, shelter_id: 48)
Pet.create(name: 'Rambo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/siberian_husky_14.jpg', age_approx: 7, sex: 'female', breed: 'Siberian Husky', adoptable: true, shelter_id: 6)
Pet.create(name: 'Ivey', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/soft-coated_wheaten_terrier_80.jpg', age_approx: 8, sex: 'female', breed: 'Soft-Coated Wheaten Terrier', adoptable: false, shelter_id: 64)
Pet.create(name: 'Coraline', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/boston_bull_64.jpg', age_approx: 9, sex: 'male', breed: 'Boston Bull', adoptable: true, shelter_id: 43)
Pet.create(name: 'Hardie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/blenheim_spaniel_6.jpg', age_approx: 11, sex: 'female', breed: 'Blenheim Spaniel', adoptable: true, shelter_id: 90)
Pet.create(name: 'Finnick', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/irish_setter_22.jpg', age_approx: 6, sex: 'female', breed: 'Irish Setter', adoptable: true, shelter_id: 21)
Pet.create(name: 'Doxie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/african_hunting_dog_102.jpg', age_approx: 2, sex: 'male', breed: 'African Hunting Dog', adoptable: true, shelter_id: 13)
Pet.create(name: 'Hirohito', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/black-and-tan_coonhound_56.jpg', age_approx: 5, sex: 'female', breed: 'Black-And-Tan Coonhound', adoptable: true, shelter_id: 85)
Pet.create(name: 'Hypnotic', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/whippet_85.jpg', age_approx: 3, sex: 'male', breed: 'Whippet', adoptable: true, shelter_id: 11)
Pet.create(name: 'Chancellor', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bedlington_terrier_113.jpg', age_approx: 1, sex: 'male', breed: 'Bedlington Terrier', adoptable: true, shelter_id: 48)
Pet.create(name: 'Andersen', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kerry_blue_terrier_80.jpg', age_approx: 11, sex: 'male', breed: 'Kerry Blue Terrier', adoptable: true, shelter_id: 56)
Pet.create(name: 'Dakar', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/west_highland_white_terrier_73.jpg', age_approx: 14, sex: 'male', breed: 'West Highland White Terrier', adoptable: true, shelter_id: 28)
Pet.create(name: 'Coco-Puff', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kelpie_78.jpg', age_approx: 15, sex: 'male', breed: 'Kelpie', adoptable: true, shelter_id: 54)
Pet.create(name: 'Maxsuki', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/redbone_142.jpg', age_approx: 4, sex: 'male', breed: 'Redbone', adoptable: true, shelter_id: 77)
Pet.create(name: 'Quille', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_setter_142.jpg', age_approx: 2, sex: 'female', breed: 'English Setter', adoptable: true, shelter_id: 59)
Pet.create(name: 'N.J.', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_setter_49.jpg', age_approx: 6, sex: 'male', breed: 'English Setter', adoptable: true, shelter_id: 101)
Pet.create(name: 'Zino', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_foxhound_117.jpg', age_approx: 4, sex: 'male', breed: 'English Foxhound', adoptable: true, shelter_id: 25)
Pet.create(name: 'Akasha', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/cocker_spaniel_21.jpg', age_approx: 15, sex: 'female', breed: 'Cocker Spaniel', adoptable: true, shelter_id: 83)
Pet.create(name: 'Geo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/great_dane_56.jpg', age_approx: 15, sex: 'male', breed: 'Great Dane', adoptable: true, shelter_id: 70)
Pet.create(name: 'Boccelli', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/chow_158.jpg', age_approx: 12, sex: 'male', breed: 'Chow', adoptable: true, shelter_id: 72)
Pet.create(name: 'Cheka', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_setter_16.jpg', age_approx: 15, sex: 'male', breed: 'English Setter', adoptable: true, shelter_id: 71)
Pet.create(name: 'Ashes', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/border_collie_64.jpg', age_approx: 13, sex: 'female', breed: 'Border Collie', adoptable: true, shelter_id: 84)
Pet.create(name: 'Wiener', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/shih-tzu_110.jpg', age_approx: 15, sex: 'male', breed: 'Shih-Tzu', adoptable: true, shelter_id: 14)
Pet.create(name: 'Saucey', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/greater_swiss_mountain_dog_150.jpg', age_approx: 5, sex: 'female', breed: 'Greater Swiss Mountain Dog', adoptable: true, shelter_id: 39)
Pet.create(name: 'Simmons', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/toy_poodle_136.jpg', age_approx: 6, sex: 'female', breed: 'Toy Poodle', adoptable: false, shelter_id: 53)
Pet.create(name: 'Snoogie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/airedale_37.jpg', age_approx: 1, sex: 'female', breed: 'Airedale', adoptable: true, shelter_id: 31)
Pet.create(name: 'Iru', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scottish_deerhound_96.jpg', age_approx: 7, sex: 'male', breed: 'Scottish Deerhound', adoptable: true, shelter_id: 84)
Pet.create(name: 'Temper', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pekinese_81.jpg', age_approx: 6, sex: 'female', breed: 'Pekinese', adoptable: true, shelter_id: 87)
Pet.create(name: 'Smithwicks', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/german_short-haired_pointer_14.jpg', age_approx: 10, sex: 'male', breed: 'German Short-Haired Pointer', adoptable: true, shelter_id: 15)
Pet.create(name: 'Touch', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_springer_100.jpg', age_approx: 3, sex: 'female', breed: 'English Springer', adoptable: false, shelter_id: 88)
Pet.create(name: 'Dozo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/standard_poodle_129.jpg', age_approx: 11, sex: 'female', breed: 'Standard Poodle', adoptable: true, shelter_id: 78)
Pet.create(name: 'Viti', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/irish_water_spaniel_26.jpg', age_approx: 15, sex: 'female', breed: 'Irish Water Spaniel', adoptable: true, shelter_id: 43)
Pet.create(name: 'Guru', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pug_175.jpg', age_approx: 2, sex: 'male', breed: 'Pug', adoptable: true, shelter_id: 45)
Pet.create(name: 'Tieta', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/afghan_hound_42.jpg', age_approx: 4, sex: 'male', breed: 'Afghan Hound', adoptable: true, shelter_id: 36)
Pet.create(name: 'Tommie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/golden_retriever_141.jpg', age_approx: 4, sex: 'male', breed: 'Golden Retriever', adoptable: true, shelter_id: 23)
Pet.create(name: 'Micke', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/cocker_spaniel_59.jpg', age_approx: 5, sex: 'female', breed: 'Cocker Spaniel', adoptable: true, shelter_id: 97)
Pet.create(name: 'Nakia', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/miniature_poodle_50.jpg', age_approx: 6, sex: 'female', breed: 'Miniature Poodle', adoptable: true, shelter_id: 41)
Pet.create(name: 'Munny', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kelpie_7.jpg', age_approx: 8, sex: 'male', breed: 'Kelpie', adoptable: true, shelter_id: 65)
Pet.create(name: 'Maeby', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scottish_deerhound_64.jpg', age_approx: 5, sex: 'female', breed: 'Scottish Deerhound', adoptable: true, shelter_id: 59)
Pet.create(name: 'Moca', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/silky_terrier_129.jpg', age_approx: 4, sex: 'female', breed: 'Silky Terrier', adoptable: true, shelter_id: 32)
Pet.create(name: 'Maimouna', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/basenji_152.jpg', age_approx: 13, sex: 'male', breed: 'Basenji', adoptable: true, shelter_id: 60)
Pet.create(name: 'Xochitl', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/rhodesian_ridgeback_16.jpg', age_approx: 8, sex: 'female', breed: 'Rhodesian Ridgeback', adoptable: false, shelter_id: 102)
Pet.create(name: 'Tahj', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/maltese_dog_87.jpg', age_approx: 7, sex: 'female', breed: 'Maltese Dog', adoptable: true, shelter_id: 7)
Pet.create(name: 'Salsita', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/affenpinscher_83.jpg', age_approx: 5, sex: 'male', breed: 'Affenpinscher', adoptable: true, shelter_id: 103)
Pet.create(name: 'Perez', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bouvier_des_flandres_31.jpg', age_approx: 4, sex: 'female', breed: 'Bouvier Des Flandres', adoptable: true, shelter_id: 76)
Pet.create(name: 'Curly', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pekinese_50.jpg', age_approx: 5, sex: 'male', breed: 'Pekinese', adoptable: true, shelter_id: 17)
Pet.create(name: 'Mazuso', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bluetick_132.jpg', age_approx: 13, sex: 'female', breed: 'Bluetick', adoptable: true, shelter_id: 89)
Pet.create(name: 'Archimedes', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bedlington_terrier_78.jpg', age_approx: 11, sex: 'female', breed: 'Bedlington Terrier', adoptable: true, shelter_id: 38)
Pet.create(name: 'Yggye', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/italian_greyhound_80.jpg', age_approx: 9, sex: 'male', breed: 'Italian Greyhound', adoptable: true, shelter_id: 18)
Pet.create(name: 'Selyce', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/lhasa_82.jpg', age_approx: 9, sex: 'male', breed: 'Lhasa', adoptable: true, shelter_id: 64)
Pet.create(name: 'Freyja', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/beagle_158.jpg', age_approx: 10, sex: 'male', breed: 'Beagle', adoptable: true, shelter_id: 37)
Pet.create(name: 'Gus-Guy', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/weimaraner_105.jpg', age_approx: 1, sex: 'male', breed: 'Weimaraner', adoptable: true, shelter_id: 82)
Pet.create(name: 'Etta', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/standard_poodle_70.jpg', age_approx: 9, sex: 'male', breed: 'Standard Poodle', adoptable: true, shelter_id: 25)
Pet.create(name: 'Albus', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/newfoundland_59.jpg', age_approx: 14, sex: 'female', breed: 'Newfoundland', adoptable: true, shelter_id: 5)
Pet.create(name: 'Clemens', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norfolk_terrier_4.jpg', age_approx: 2, sex: 'male', breed: 'Norfolk Terrier', adoptable: true, shelter_id: 61)
Pet.create(name: 'Barklee', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/maltese_dog_204.jpg', age_approx: 15, sex: 'male', breed: 'Maltese Dog', adoptable: true, shelter_id: 64)
Pet.create(name: 'Bug', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scotch_terrier_17.jpg', age_approx: 2, sex: 'male', breed: 'Scotch Terrier', adoptable: true, shelter_id: 70)
Pet.create(name: 'Vicki', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/entlebucher_31.jpg', age_approx: 15, sex: 'female', breed: 'Entlebucher', adoptable: true, shelter_id: 71)
Pet.create(name: 'Neal', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/staffordshire_bullterrier_144.jpg', age_approx: 6, sex: 'male', breed: 'Staffordshire Bullterrier', adoptable: true, shelter_id: 96)
Pet.create(name: 'Fielding', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/great_dane_17.jpg', age_approx: 8, sex: 'male', breed: 'Great Dane', adoptable: true, shelter_id: 8)
Pet.create(name: 'Pet', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/chow_43.jpg', age_approx: 11, sex: 'female', breed: 'Chow', adoptable: false, shelter_id: 11)
Pet.create(name: 'Felix', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/papillon_154.jpg', age_approx: 2, sex: 'female', breed: 'Papillon', adoptable: true, shelter_id: 98)
Pet.create(name: 'Kosar', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/irish_water_spaniel_144.jpg', age_approx: 10, sex: 'female', breed: 'Irish Water Spaniel', adoptable: true, shelter_id: 5)
Pet.create(name: 'Chalkee', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/saluki_58.jpg', age_approx: 8, sex: 'female', breed: 'Saluki', adoptable: true, shelter_id: 65)
Pet.create(name: 'Gigabyte', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/samoyed_114.jpg', age_approx: 6, sex: 'male', breed: 'Samoyed', adoptable: true, shelter_id: 101)
Pet.create(name: 'Chandi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/brabancon_griffon_36.jpg', age_approx: 10, sex: 'male', breed: 'Brabancon Griffon', adoptable: true, shelter_id: 104)
Pet.create(name: 'Bri', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norfolk_terrier_71.jpg', age_approx: 7, sex: 'female', breed: 'Norfolk Terrier', adoptable: true, shelter_id: 80)
Pet.create(name: 'Alli', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/japanese_spaniel_168.jpg', age_approx: 6, sex: 'male', breed: 'Japanese Spaniel', adoptable: true, shelter_id: 95)
Pet.create(name: 'Pretzel', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/west_highland_white_terrier_122.jpg', age_approx: 13, sex: 'male', breed: 'West Highland White Terrier', adoptable: true, shelter_id: 35)
Pet.create(name: 'Alara', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/rhodesian_ridgeback_165.jpg', age_approx: 7, sex: 'male', breed: 'Rhodesian Ridgeback', adoptable: true, shelter_id: 47)
Pet.create(name: 'Pernault', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/australian_terrier_105.jpg', age_approx: 5, sex: 'male', breed: 'Australian Terrier', adoptable: true, shelter_id: 76)
Pet.create(name: 'Lady', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/staffordshire_bullterrier_147.jpg', age_approx: 1, sex: 'male', breed: 'Staffordshire Bullterrier', adoptable: true, shelter_id: 59)
Pet.create(name: 'Bacchio', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kuvasz_74.jpg', age_approx: 3, sex: 'female', breed: 'Kuvasz', adoptable: true, shelter_id: 51)
Pet.create(name: 'Erm', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/toy_poodle_132.jpg', age_approx: 7, sex: 'female', breed: 'Toy Poodle', adoptable: true, shelter_id: 15)
Pet.create(name: 'Toa', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/cairn_136.jpg', age_approx: 9, sex: 'male', breed: 'Cairn', adoptable: true, shelter_id: 56)
Pet.create(name: 'Prinsesa', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/lhasa_67.jpg', age_approx: 11, sex: 'female', breed: 'Lhasa', adoptable: true, shelter_id: 72)
Pet.create(name: 'Alexander', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/siberian_husky_5.jpg', age_approx: 5, sex: 'female', breed: 'Siberian Husky', adoptable: true, shelter_id: 63)
Pet.create(name: 'Tulsi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/entlebucher_171.jpg', age_approx: 5, sex: 'male', breed: 'Entlebucher', adoptable: true, shelter_id: 96)
Pet.create(name: 'Eight', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/boxer_66.jpg', age_approx: 2, sex: 'male', breed: 'Boxer', adoptable: true, shelter_id: 71)
Pet.create(name: 'Hiroshi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/african_hunting_dog_46.jpg', age_approx: 5, sex: 'female', breed: 'African Hunting Dog', adoptable: true, shelter_id: 58)
Pet.create(name: 'Stonewall', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/silky_terrier_22.jpg', age_approx: 13, sex: 'male', breed: 'Silky Terrier', adoptable: true, shelter_id: 63)
Pet.create(name: 'Lunysol', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/english_setter_59.jpg', age_approx: 3, sex: 'female', breed: 'English Setter', adoptable: true, shelter_id: 91)
Pet.create(name: 'Pashmak', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/dingo_33.jpg', age_approx: 6, sex: 'female', breed: 'Dingo', adoptable: true, shelter_id: 39)
Pet.create(name: 'Roxi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/malamute_8.jpg', age_approx: 13, sex: 'male', breed: 'Malamute', adoptable: true, shelter_id: 74)
Pet.create(name: 'Dawg', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bloodhound_30.jpg', age_approx: 1, sex: 'male', breed: 'Bloodhound', adoptable: true, shelter_id: 38)
Pet.create(name: 'Yugy', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/whippet_99.jpg', age_approx: 6, sex: 'female', breed: 'Whippet', adoptable: true, shelter_id: 100)
Pet.create(name: 'Wembley', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/french_bulldog_45.jpg', age_approx: 3, sex: 'female', breed: 'French Bulldog', adoptable: true, shelter_id: 74)
Pet.create(name: 'Nonye', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/otterhound_43.jpg', age_approx: 5, sex: 'male', breed: 'Otterhound', adoptable: true, shelter_id: 28)
Pet.create(name: 'Drejas', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/saluki_109.jpg', age_approx: 8, sex: 'female', breed: 'Saluki', adoptable: false, shelter_id: 62)
Pet.create(name: 'Choupi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/beagle_128.jpg', age_approx: 6, sex: 'female', breed: 'Beagle', adoptable: true, shelter_id: 45)
Pet.create(name: 'Atreyu', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/japanese_spaniel_42.jpg', age_approx: 10, sex: 'female', breed: 'Japanese Spaniel', adoptable: false, shelter_id: 99)
Pet.create(name: 'Oran', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/dandie_dinmont_114.jpg', age_approx: 13, sex: 'male', breed: 'Dandie Dinmont', adoptable: true, shelter_id: 69)
Pet.create(name: 'Schodack', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/schipperke_110.jpg', age_approx: 8, sex: 'female', breed: 'Schipperke', adoptable: true, shelter_id: 13)
Pet.create(name: 'Bronxbully', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scotch_terrier_38.jpg', age_approx: 8, sex: 'female', breed: 'Scotch Terrier', adoptable: true, shelter_id: 80)
Pet.create(name: 'Saina', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/gordon_setter_20.jpg', age_approx: 3, sex: 'male', breed: 'Gordon Setter', adoptable: true, shelter_id: 22)
Pet.create(name: 'Oopla', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/toy_poodle_41.jpg', age_approx: 8, sex: 'male', breed: 'Toy Poodle', adoptable: true, shelter_id: 72)
Pet.create(name: 'Gaston', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norwich_terrier_180.jpg', age_approx: 3, sex: 'female', breed: 'Norwich Terrier', adoptable: true, shelter_id: 50)
Pet.create(name: 'Malabu', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kerry_blue_terrier_135.jpg', age_approx: 3, sex: 'male', breed: 'Kerry Blue Terrier', adoptable: true, shelter_id: 28)
Pet.create(name: 'Zarina', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/basenji_148.jpg', age_approx: 6, sex: 'female', breed: 'Basenji', adoptable: true, shelter_id: 90)
Pet.create(name: 'Hanna', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/ibizan_hound_87.jpg', age_approx: 10, sex: 'female', breed: 'Ibizan Hound', adoptable: true, shelter_id: 96)
Pet.create(name: 'Walter', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/sussex_spaniel_134.jpg', age_approx: 8, sex: 'female', breed: 'Sussex Spaniel', adoptable: true, shelter_id: 19)
Pet.create(name: 'Avo', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kuvasz_146.jpg', age_approx: 12, sex: 'male', breed: 'Kuvasz', adoptable: true, shelter_id: 104)
Pet.create(name: 'Coco-Bella', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/sealyham_terrier_155.jpg', age_approx: 14, sex: 'male', breed: 'Sealyham Terrier', adoptable: true, shelter_id: 100)
Pet.create(name: 'Birol', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/airedale_197.jpg', age_approx: 6, sex: 'male', breed: 'Airedale', adoptable: true, shelter_id: 36)
Pet.create(name: 'Taraniuk', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/black-and-tan_coonhound_115.jpg', age_approx: 1, sex: 'male', breed: 'Black-And-Tan Coonhound', adoptable: true, shelter_id: 28)
Pet.create(name: 'Farroupilha', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/boston_bull_163.jpg', age_approx: 11, sex: 'female', breed: 'Boston Bull', adoptable: true, shelter_id: 71)
Pet.create(name: 'Knightly', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/miniature_schnauzer_124.jpg', age_approx: 15, sex: 'female', breed: 'Miniature Schnauzer', adoptable: true, shelter_id: 104)
Pet.create(name: 'Aeon', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/leonberg_59.jpg', age_approx: 15, sex: 'female', breed: 'Leonberg', adoptable: true, shelter_id: 43)
Pet.create(name: 'Amba', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/maltese_dog_45.jpg', age_approx: 5, sex: 'male', breed: 'Maltese Dog', adoptable: true, shelter_id: 43)
Pet.create(name: 'Eisley', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kelpie_118.jpg', age_approx: 10, sex: 'female', breed: 'Kelpie', adoptable: true, shelter_id: 82)
Pet.create(name: 'Osi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/ibizan_hound_84.jpg', age_approx: 11, sex: 'male', breed: 'Ibizan Hound', adoptable: true, shelter_id: 56)
Pet.create(name: 'August', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/keeshond_43.jpg', age_approx: 9, sex: 'male', breed: 'Keeshond', adoptable: true, shelter_id: 46)
Pet.create(name: 'Ellie/Eloise', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/whippet_152.jpg', age_approx: 4, sex: 'male', breed: 'Whippet', adoptable: true, shelter_id: 51)
Pet.create(name: 'Chutney', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/bernese_mountain_dog_209.jpg', age_approx: 14, sex: 'female', breed: 'Bernese Mountain Dog', adoptable: false, shelter_id: 49)
Pet.create(name: 'Petri', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/mexican_hairless_33.jpg', age_approx: 12, sex: 'male', breed: 'Mexican Hairless', adoptable: true, shelter_id: 56)
Pet.create(name: 'Fredrico', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/staffordshire_bullterrier_69.jpg', age_approx: 3, sex: 'male', breed: 'Staffordshire Bullterrier', adoptable: true, shelter_id: 39)
Pet.create(name: 'Pinkman', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/norwegian_elkhound_101.jpg', age_approx: 6, sex: 'female', breed: 'Norwegian Elkhound', adoptable: true, shelter_id: 48)
Pet.create(name: 'Bleecker', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/curly-coated_retriever_95.jpg', age_approx: 9, sex: 'female', breed: 'Curly-Coated Retriever', adoptable: true, shelter_id: 100)
Pet.create(name: 'Cacau', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/entlebucher_21.jpg', age_approx: 3, sex: 'female', breed: 'Entlebucher', adoptable: true, shelter_id: 44)
Pet.create(name: 'Marta', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/saint_bernard_124.jpg', age_approx: 6, sex: 'male', breed: 'Saint Bernard', adoptable: true, shelter_id: 65)
Pet.create(name: 'Boarbon', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/vizsla_11.jpg', age_approx: 2, sex: 'female', breed: 'Vizsla', adoptable: true, shelter_id: 96)
Pet.create(name: 'Phiere', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/weimaraner_113.jpg', age_approx: 13, sex: 'male', breed: 'Weimaraner', adoptable: true, shelter_id: 68)
Pet.create(name: 'Wells', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/staffordshire_bullterrier_66.jpg', age_approx: 6, sex: 'female', breed: 'Staffordshire Bullterrier', adoptable: true, shelter_id: 84)
Pet.create(name: 'Booster', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/kuvasz_114.jpg', age_approx: 9, sex: 'female', breed: 'Kuvasz', adoptable: true, shelter_id: 74)
Pet.create(name: 'Semi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/lakeland_terrier_195.jpg', age_approx: 15, sex: 'male', breed: 'Lakeland Terrier', adoptable: true, shelter_id: 102)
Pet.create(name: 'Coffey', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/siberian_husky_41.jpg', age_approx: 10, sex: 'male', breed: 'Siberian Husky', adoptable: true, shelter_id: 65)
Pet.create(name: 'Aries', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/border_terrier_73.jpg', age_approx: 9, sex: 'female', breed: 'Border Terrier', adoptable: true, shelter_id: 94)
Pet.create(name: 'Mayi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/brabancon_griffon_66.jpg', age_approx: 10, sex: 'female', breed: 'Brabancon Griffon', adoptable: true, shelter_id: 74)
Pet.create(name: 'Kearsarge', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/borzoi_110.jpg', age_approx: 11, sex: 'male', breed: 'Borzoi', adoptable: true, shelter_id: 65)
Pet.create(name: 'Peany', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/toy_poodle_26.jpg', age_approx: 15, sex: 'female', breed: 'Toy Poodle', adoptable: true, shelter_id: 85)
Pet.create(name: 'Ryeana', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/doberman_104.jpg', age_approx: 1, sex: 'female', breed: 'Doberman', adoptable: true, shelter_id: 81)
Pet.create(name: 'Natalie', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/basset_113.jpg', age_approx: 10, sex: 'female', breed: 'Basset', adoptable: true, shelter_id: 49)
Pet.create(name: 'Nyra', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/old_english_sheepdog_5.jpg', age_approx: 4, sex: 'female', breed: 'Old English Sheepdog', adoptable: true, shelter_id: 46)
Pet.create(name: 'Dami', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/flat-coated_retriever_92.jpg', age_approx: 11, sex: 'male', breed: 'Flat-Coated Retriever', adoptable: true, shelter_id: 90)
Pet.create(name: 'Xiqui', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pug_117.jpg', age_approx: 8, sex: 'male', breed: 'Pug', adoptable: true, shelter_id: 104)
Pet.create(name: 'Bomi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/shetland_sheepdog_58.jpg', age_approx: 15, sex: 'male', breed: 'Shetland Sheepdog', adoptable: true, shelter_id: 83)
Pet.create(name: 'Cachaca', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pekinese_24.jpg', age_approx: 15, sex: 'female', breed: 'Pekinese', adoptable: true, shelter_id: 7)
Pet.create(name: 'Gesha', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/staffordshire_bullterrier_93.jpg', age_approx: 14, sex: 'male', breed: 'Staffordshire Bullterrier', adoptable: true, shelter_id: 40)
Pet.create(name: 'Churchill', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/standard_poodle_63.jpg', age_approx: 7, sex: 'male', breed: 'Standard Poodle', adoptable: true, shelter_id: 51)
Pet.create(name: 'Rosas', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/clumber_135.jpg', age_approx: 1, sex: 'female', breed: 'Clumber', adoptable: false, shelter_id: 42)
Pet.create(name: 'Moty', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pomeranian_130.jpg', age_approx: 5, sex: 'female', breed: 'Pomeranian', adoptable: true, shelter_id: 74)
Pet.create(name: 'Delila', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/scottish_deerhound_38.jpg', age_approx: 11, sex: 'female', breed: 'Scottish Deerhound', adoptable: true, shelter_id: 90)
Pet.create(name: 'Laudzinski', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/italian_greyhound_118.jpg', age_approx: 8, sex: 'male', breed: 'Italian Greyhound', adoptable: true, shelter_id: 53)
Pet.create(name: 'Liqos', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/japanese_spaniel_95.jpg', age_approx: 14, sex: 'male', breed: 'Japanese Spaniel', adoptable: true, shelter_id: 64)
Pet.create(name: 'Chowchow', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/greater_swiss_mountain_dog_87.jpg', age_approx: 1, sex: 'male', breed: 'Greater Swiss Mountain Dog', adoptable: true, shelter_id: 66)
Pet.create(name: 'Henrik', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/boston_bull_35.jpg', age_approx: 3, sex: 'female', breed: 'Boston Bull', adoptable: true, shelter_id: 30)
Pet.create(name: 'Whitaker', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/papillon_121.jpg', age_approx: 5, sex: 'female', breed: 'Papillon', adoptable: true, shelter_id: 90)
Pet.create(name: 'Shae', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/pug_114.jpg', age_approx: 5, sex: 'male', breed: 'Pug', adoptable: true, shelter_id: 8)
Pet.create(name: 'Alvarenga', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/old_english_sheepdog_28.jpg', age_approx: 12, sex: 'female', breed: 'Old English Sheepdog', adoptable: true, shelter_id: 49)
Pet.create(name: 'Rajah', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/vizsla_46.jpg', age_approx: 14, sex: 'male', breed: 'Vizsla', adoptable: true, shelter_id: 9)
Pet.create(name: 'Finnigan', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/australian_terrier_169.jpg', age_approx: 3, sex: 'female', breed: 'Australian Terrier', adoptable: true, shelter_id: 51)
Pet.create(name: 'Mooshi', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/cairn_68.jpg', age_approx: 7, sex: 'female', breed: 'Cairn', adoptable: true, shelter_id: 8)
Pet.create(name: 'Oliebol', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/siberian_husky_123.jpg', age_approx: 15, sex: 'male', breed: 'Siberian Husky', adoptable: true, shelter_id: 57)
Pet.create(name: 'Michelle', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/miniature_pinscher_10.jpg', age_approx: 5, sex: 'female', breed: 'Miniature Pinscher', adoptable: true, shelter_id: 88)
Pet.create(name: 'Campanita', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/cocker_spaniel_64.jpg', age_approx: 2, sex: 'male', breed: 'Cocker Spaniel', adoptable: true, shelter_id: 86)
Pet.create(name: 'Ohren', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/mexican_hairless_29.jpg', age_approx: 6, sex: 'female', breed: 'Mexican Hairless', adoptable: true, shelter_id: 95)
Pet.create(name: 'Spongeky', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/sealyham_terrier_48.jpg', age_approx: 8, sex: 'female', breed: 'Sealyham Terrier', adoptable: true, shelter_id: 38)
Pet.create(name: 'Akeelah', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/irish_wolfhound_180.jpg', age_approx: 2, sex: 'female', breed: 'Irish Wolfhound', adoptable: true, shelter_id: 77)
Pet.create(name: 'Pinocchio', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/chesapeake_bay_retriever_10.jpg', age_approx: 8, sex: 'male', breed: 'Chesapeake Bay Retriever', adoptable: true, shelter_id: 102)
Pet.create(name: 'Phedora', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/tibetan_terrier_19.jpg', age_approx: 3, sex: 'female', breed: 'Tibetan Terrier', adoptable: true, shelter_id: 10)
Pet.create(name: 'Bokka', image: 'https://adopt-dont-shop.s3-us-west-1.amazonaws.com/images/tibetan_terrier_95.jpg', age_approx: 9, sex: 'male', breed: 'Tibetan Terrier', adoptable: true, shelter_id: 66)
