# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Shelter.create(name: 'Alamo Lake Dog Haven', address: '12 Ferry Avenue', city: 'Cincinnati', state: 'Ohio', zip: 45219)
# Shelter.create(name: 'Alcova Dog Shelter', address: '67 Jefferson Lane', city: 'El Paso', state: 'Texas', zip: 79901)
# Shelter.create(name: 'Alpine Northeast Dog Haven', address: '25 Jessie Avenue', city: 'Springfield', state: 'Massachusetts', zip: 21151)
# Shelter.create(name: 'Anoka Dog Sanctuary', address: '60 Loma Street', city: 'Dallas', state: 'Texas', zip: 75287)
# Shelter.create(name: 'Antelope Hills Dog Sanctuary', address: '41 Renfrow Street', city: 'Tucson', state: 'Arizona', zip: 85705)
# Shelter.create(name: 'Atlantic City Dog Sanctuary', address: '59 Pine Valley Street', city: 'Sarasota', state: 'Florida', zip: 34232)
# Shelter.create(name: 'Beluga Dog Shelter', address: '72 Strong Lane', city: 'Indianapolis', state: 'Indiana', zip: 46218)
# Shelter.create(name: 'Birch Creek Dog Haven', address: '11 Corning Avenue', city: 'Milwaukee', state: 'Wisconsin', zip: 53203)
# Shelter.create(name: 'Bondurant Dog Shelter', address: '78 Pillsbury Lane', city: 'Colorado Springs', state: 'Colorado', zip: 80951)
# Shelter.create(name: 'Boulder Dog Sanctuary', address: '43 Lake Buena Vista Street', city: 'Rochester', state: 'New York', zip: 14608)
# Shelter.create(name: 'Bowden Dog Sanctuary', address: '54 Meyer Street', city: 'Buffalo', state: 'New York', zip: 14208)
# Shelter.create(name: 'Brownlee Dog Haven', address: '25 New Holland Avenue', city: 'Minneapolis', state: 'Minnesota', zip: 55403)
# Shelter.create(name: 'Brundage Dog Haven', address: '4 Zarephath Avenue', city: 'Reno', state: 'Nevada', zip: 89521)
# Shelter.create(name: 'Butterfield Dog Sanctuary', address: '44 Topock Street', city: 'Las Vegas', state: 'Nevada', zip: 89107)
# Shelter.create(name: 'Canova Dog Haven', address: '13 Junction City Avenue', city: 'Baton Rouge', state: 'Louisiana', zip: 70836)
# Shelter.create(name: 'Carter Dog Sanctuary', address: '53 Kingston Street', city: 'Allentown', state: 'Pennsylvania', zip: 18105)
# Shelter.create(name: 'Cave Dog Haven', address: '24 Weed Avenue', city: 'Brooklyn', state: 'New York', zip: 11212)
# Shelter.create(name: 'City of the Sun Dog Sanctuary', address: '61 Paxson Street', city: 'Ogden', state: 'Utah', zip: 84404)
# Shelter.create(name: 'Cobre Dog Haven', address: '20 Burton Avenue', city: 'Worcester', state: 'Massachusetts', zip: 41610)
# Shelter.create(name: 'Conchas Dam Dog Shelter', address: '81 East Amana Lane', city: 'Mission Viejo', state: 'California', zip: 92692)
# Shelter.create(name: 'Cuevitas Dog Shelter', address: '77 Knowles Lane', city: 'Des Moines', state: 'Iowa', zip: 50309)
# Shelter.create(name: 'Donald Dog Sanctuary', address: '40 Whitmer Street', city: 'Memphis', state: 'Tennessee', zip: 38120)
# Shelter.create(name: 'Escondida Dog Shelter', address: '96 Valley Ranch Lane', city: 'Palm Bay', state: 'Florida', zip: 32909)
# Shelter.create(name: 'Fontenelle Dog Haven', address: '29 Thomasville Avenue', city: 'Omaha', state: 'Nebraska', zip: 68112)
# Shelter.create(name: 'Freeport Dog Shelter', address: '81 Santa Cruz Lane', city: 'Cleveland', state: 'Ohio', zip: 44135)
# Shelter.create(name: 'Funkley Dog Haven', address: '29 San Antonio Avenue', city: 'Queens', state: 'New York', zip: 11361)
# Shelter.create(name: 'Gann Valley Dog Shelter', address: '71 Kief Lane', city: 'Riverside', state: 'California', zip: 92508)
# Shelter.create(name: 'Garfield Dog Shelter', address: '68 Albee Lane', city: 'Tampa', state: 'Florida', zip: 33637)
# Shelter.create(name: 'Garfield Dog Shelter', address: '100 Larson Lane', city: 'Provo', state: 'Utah', zip: 84604)
# Shelter.create(name: 'Gross Dog Shelter', address: '99 Towner Lane', city: 'Columbus', state: 'Ohio', zip: 43026)
# Shelter.create(name: 'Guerra Dog Shelter', address: '76 Farmer Lane', city: 'Denton', state: 'Texas', zip: 76207)
# Shelter.create(name: 'Hawk Springs Dog Shelter', address: '68 Charco Lane', city: 'Hartford', state: 'Connecticut', zip: 06106)
# Shelter.create(name: 'Healy Lake Dog Shelter', address: '90 Plevna Lane', city: 'San Antonio', state: 'Texas', zip: 78112)
# Shelter.create(name: 'Heimdal Dog Sanctuary', address: '50 Weeki Wachee Street', city: 'Sacramento', state: 'California', zip: 95820)
# Shelter.create(name: 'Helen Dog Shelter', address: '83 Valley City Lane', city: 'Bridgeport', state: 'Connecticut', zip: 06605)
# Shelter.create(name: 'Hillside Acres Dog Sanctuary', address: '65 Abeytas Street', city: 'Port St. Lucie', state: 'Florida', zip: 34986)
# Shelter.create(name: 'Hillsview Dog Haven', address: '16 Bettles Avenue', city: 'Austin', state: 'Texas', zip: 78749)
# Shelter.create(name: 'Hoot Owl Dog Haven', address: '16 Amistad Avenue', city: 'Orlando', state: 'Florida', zip: 32829)
# Shelter.create(name: 'Huntley Dog Shelter', address: '98 Conway Lane', city: 'Dayton', state: 'Ohio', zip: 45432)
# Shelter.create(name: 'Jeffrey City Dog Sanctuary', address: '46 Excello Street', city: 'McAllen', state: 'Texas', zip: 78573)
# Shelter.create(name: 'Kelly Dog Sanctuary', address: '47 Ugashik Street', city: 'Cape Coral', state: 'Florida', zip: 33991)
# Shelter.create(name: 'Ketron Island Dog Sanctuary', address: '46 Milltown Street', city: 'Salt Lake City', state: 'Utah', zip: 84116)
# Shelter.create(name: 'Lake Roberts Dog Shelter', address: '74 Athelstan Lane', city: 'Wichita', state: 'Kansas', zip: 67230)
# Shelter.create(name: 'Lambert Dog Haven', address: '2 Beaconsfield Avenue', city: 'Boston', state: 'Massachusetts', zip: 02120)
# Shelter.create(name: 'Laurier Dog Haven', address: '8 Bartow Avenue', city: 'Nashville', state: 'Tennessee', zip: 37027)
# Shelter.create(name: 'Lily Dog Shelter', address: '76 Gulkana Lane', city: 'Pittsburgh', state: 'Pennsylvania', zip: 15216)
# Shelter.create(name: 'Lime Village Dog Sanctuary', address: '62 Virgil Street', city: 'Chicago', state: 'Illinois', zip: 60018)
# Shelter.create(name: 'Lonetree Dog Sanctuary', address: '60 Lost River Street', city: 'Fort Worth', state: 'Texas', zip: 76164)
# Shelter.create(name: 'Los Lobos Dog Sanctuary', address: '60 Waldron Street', city: 'Long Beach', state: 'California', zip: 90822)
# Shelter.create(name: 'Lost Springs Dog Haven', address: '26 Le Roy Avenue', city: 'St. Louis', state: 'Missouri', zip: 63110)
# Shelter.create(name: 'Lotsee Dog Sanctuary', address: '39 Megargel Street', city: 'Virginia Beach', state: 'Virginia', zip: 23459)
# Shelter.create(name: 'Lower Frisco Dog Sanctuary', address: '46 Lance Creek Street', city: 'Bakersfield', state: 'California', zip: 93306)
# Shelter.create(name: 'Lowry Dog Sanctuary', address: '36 Cooperton Street', city: 'Seattle', state: 'Washington', zip: 98109)
# Shelter.create(name: 'Manzano Dog Sanctuary', address: '42 Stevens Village Street', city: 'New Haven', state: 'Connecticut', zip: 66519)
# Shelter.create(name: 'Marblemount Dog Sanctuary', address: '44 Pine Island Street', city: 'Richmond', state: 'Virginia', zip: 23222)
# Shelter.create(name: 'Martinez Dog Haven', address: '20 River Bend Avenue', city: 'Staten Island', state: 'New York', zip: 10302)
# Shelter.create(name: 'McKinnon Dog Sanctuary', address: '46 Cartago Street', city: 'Grand Rapids', state: 'Michigan', zip: 49546)
# Shelter.create(name: 'McLeod Dog Sanctuary', address: '44 Onaka Street', city: 'San Diego', state: 'California', zip: 92109)
# Shelter.create(name: 'Moclips Dog Sanctuary', address: '45 Churchs Ferry Street', city: 'Raleigh', state: 'North Carolina', zip: 27617)
# Shelter.create(name: 'Monowi Dog Haven', address: '6 Champ Avenue', city: 'Providence', state: 'Rhode Island', zip: 92903)
# Shelter.create(name: 'Newkirk Dog Shelter', address: '98 Raleigh Lane', city: 'Akron', state: 'Ohio', zip: 44306)
# Shelter.create(name: 'Oakley Dog Shelter', address: '84 Loveland Lane', city: 'Honolulu', state: 'Hawaii', zip: 96859)
# Shelter.create(name: 'Odanah Dog Haven', address: '31 Valdez Avenue', city: 'Oklahoma City', state: 'Oklahoma', zip: 73012)
# Shelter.create(name: 'Orin Dog Sanctuary', address: '56 Guadalupe Guerra Street', city: 'Tulsa', state: 'Oklahoma', zip: 74133)
# Shelter.create(name: 'Owl Creek Dog Haven', address: '23 Kinbrae Avenue', city: 'Albuquerque', state: 'New Mexico', zip: 87121)
# Shelter.create(name: 'Oyehut Dog Sanctuary', address: '45 Venturia Street', city: 'Louisville', state: 'Kentucky', zip: 40177)
# Shelter.create(name: 'Pastura Dog Haven', address: '12 Dalton Avenue', city: 'Los Angeles', state: 'California', zip: 90291)
# Shelter.create(name: 'Pecan Park Dog Shelter', address: '99 Tonsina Lane', city: 'Columbia', state: 'South Carolina', zip: 29202)
# Shelter.create(name: 'Pinhook Dog Sanctuary', address: '44 Cedar Street', city: 'Jacksonville', state: 'Florida', zip: 32224)
# Shelter.create(name: 'Pinon Dog Haven', address: '8 Centralia Avenue', city: 'Mesa', state: 'Arizona', zip: 85208)
# Shelter.create(name: 'Posey Dog Sanctuary', address: '66 Van Tassell Street', city: 'Denver', state: 'Colorado', zip: 80264)
# Shelter.create(name: 'Poso Park Dog Shelter', address: '94 Valley-Hi Lane', city: 'Washington', state: 'District of Columbia', zip: 20010)
# Shelter.create(name: 'Powder River Dog Haven', address: '27 Hope Avenue', city: 'Concord', state: 'California', zip: 94518)
# Shelter.create(name: 'Pueblo Dog Shelter', address: '97 McBaine Lane', city: 'Albany', state: 'New York', zip: 12208)
# Shelter.create(name: 'Quail Dog Haven', address: '31 Clear Creek Avenue', city: 'Portland', state: 'Oregon', zip: 97227)
# Shelter.create(name: 'Regina Dog Haven', address: '31 Deputy Avenue', city: 'Murrieta', state: 'California', zip: 92563)
# Shelter.create(name: 'Rentchler Dog Haven', address: '24 McGee Creek Avenue', city: 'Atlanta', state: 'Georgia', zip: 30334)
# Shelter.create(name: 'Rivers Dog Shelter', address: '74 Roy Lake Lane', city: 'Knoxville', state: 'Tennessee', zip: 37918)
# Shelter.create(name: 'Roswell Dog Haven', address: '9 Dresser Avenue', city: 'Bronx', state: 'New York', zip: 10453)
# Shelter.create(name: 'Ruso Dog Sanctuary', address: '34 Girard Street', city: 'San Jose', state: 'California', zip: 95118)
# Shelter.create(name: 'Ryan Park Dog Haven', address: '0 St. Charles Avenue', city: 'Birmingham', state: 'Alabama', zip: 35218)
# Shelter.create(name: 'Silvana Dog Sanctuary', address: '57 Chicken Street', city: 'New Orleans', state: 'Louisiana', zip: 70139)
# Shelter.create(name: 'Sunset Acres Dog Sanctuary', address: '50 Cottonwood Street', city: 'Madison', state: 'Wisconsin', zip: 53706)
# Shelter.create(name: 'Sutton Dog Haven', address: '10 Leith Avenue', city: 'Miami', state: 'Florida', zip: 33129)
# Shelter.create(name: 'Table Rock Dog Shelter', address: '74 Dering Harbor Lane', city: 'Charleston', state: 'South Carolina', zip: 29414)
# Shelter.create(name: 'Tanquecitos South Acres II Dog Shelter', address: '68 Greenhorn Lane', city: 'Harrisburg', state: 'Pennsylvania', zip: 17101)
# Shelter.create(name: 'Tavistock Dog Haven', address: '32 Huson Avenue', city: 'Detroit', state: 'Michigan', zip: 48209)
# Shelter.create(name: 'The Ranch Dog Shelter', address: '94 Kaskaskia Lane', city: 'Charlotte', state: 'North Carolina', zip: 28269)
# Shelter.create(name: 'Three Creeks Dog Sanctuary', address: '52 Port Tobacco Village Street', city: 'Phoenix', state: 'Arizona', zip: 85008)
# Shelter.create(name: 'Thurmond Dog Shelter', address: '68 Barry Lane', city: 'San Francisco', state: 'California', zip: 94130)
# Shelter.create(name: 'Tierra Dorada Dog Shelter', address: '69 Niarada Lane', city: 'Greenville', state: 'South Carolina', zip: 29614)
# Shelter.create(name: 'Trout Valley Dog Shelter', address: '84 Keeler Lane', city: 'Toledo', state: 'Ohio', zip: 43615)
# Shelter.create(name: 'Valle Verde Dog Sanctuary', address: '57 Silver Gate Street', city: 'Little Rock', state: 'Arkansas', zip: 72211)
# Shelter.create(name: 'Verdon Dog Shelter', address: '73 Hannah Lane', city: 'Baltimore', state: 'Maryland', zip: 21218)
# Shelter.create(name: 'Warm River Dog Shelter', address: '80 Whale Pass Lane', city: 'Manhattan', state: 'New York', zip: 10026)
# Shelter.create(name: 'Westerville Dog Shelter', address: '90 Gascoyne Lane', city: 'Houston', state: 'Texas', zip: 77069)
# Shelter.create(name: 'Westlake Dog Haven', address: '11 Old Eucha Avenue', city: 'New York', state: 'New York', zip: 11229)
# Shelter.create(name: 'Westview Circle Dog Haven', address: '16 Duran Avenue', city: 'Fresno', state: 'California', zip: 93730)
# Shelter.create(name: 'White Rock Dog Haven', address: '2 Hansboro Avenue', city: 'Kansas City', state: 'Missouri', zip: 64161)
# Shelter.create(name: 'Willow Island Dog Sanctuary', address: '37 Auburn Street', city: 'Philadelphia', state: 'Pennsylvania', zip: 19154)
